---
# https://docs.docker.com/install/linux/docker-ce/debian/

- name: Ensure old versions of Docker are not installed.
  apt:
    pkg: "{{ item }}"
    state: absent
    autoremove: yes
    purge: yes
  with_items:
    - docker
    - docker-engine
    - docker.io

# Fix for buster: ImportError: No module named ssl_match_hostname
# have to install python-backports.ssl-match-hostname prior to Pip installation!
# https://github.com/docker/docker-py/issues/1502#issuecomment-509898861
- name: Ensure that python-backports.ssl module is installed.
  apt:
    pkg: python-backports.ssl-match-hostname
    state: present
  when: ansible_distribution == "Debian" and ansible_distribution_release == "buster"

- name: Install pre-requisite packages for Docker and docker-compose
  apt:
    pkg: "{{ item }}"
    state: present
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg2
    - software-properties-common
    - python-pip

- name: Add Docker apt Debian key.
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    id: 0EBFCD88
    state: present

- name: Add Docker Debian repository.
  apt_repository:
    repo: "deb https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
    state: present
    update_cache: yes

- name: Install Docker.
  apt:
    pkg: docker-ce
    state: present
