---
- name: Prevent asking for interactive input in nextcloud.sh by removing read prompts.
  replace:
    path: "{{ mc_install_dir }}/helper-scripts/nextcloud.sh"
    regexp: "^[ ]*read -"
    replace: "  : #read -"
    backup: yes

- name: Prevent errors due to docker tty.
  replace:
    path: "{{ mc_install_dir }}/helper-scripts/nextcloud.sh"
    regexp: "docker exec -it"
    replace: "docker exec -i"

- name: Prevent curl progress bar; make silent downloads.
  replace:
    path: "{{ mc_install_dir }}/helper-scripts/nextcloud.sh"
    regexp: "curl -L#"
    replace: "curl -Ls"

- name: Set subdomain name in nextcloud.sh.
  replace:
    path: "{{ mc_install_dir }}/helper-scripts/nextcloud.sh"
    regexp: "NC_SUBD=$"
    replace: "NC_SUBD={{ mc_nextcloud_subdomain }}.{{ mc_domain }}"

- name: Run NextCloud installer (only runs once).
  shell: ./nextcloud.sh --install
  args:
    executable: /bin/bash
    chdir: "{{ mc_install_dir }}/helper-scripts/"
    creates: "{{ mc_install_dir }}/data/web/nextcloud/index.php"
  environment:
    NC_CONT_FAIL: "yes"
