---
### Download, configure and install mailcow-dockerized.

- name: Clone mailcow repo.
  git:
    repo: https://github.com/mailcow/mailcow-dockerized
    version: master
    dest: "{{ mc_install_dir }}"
    clone: yes
    update: yes
    force: yes

- name: Create a generate_config_non_interactive file with settings from template.
  template:
    src: generate_config_non_interactive.j2
    dest: "{{ mc_install_dir }}/generate_config_non_interactive.sh"
    mode: a+x

- name: Append only the non-interactive portion of generate_config.sh.
  shell: cat generate_config.sh | sed -n -e '/cat << EOF > mailcow.conf/,$p' >> generate_config_non_interactive.sh
  args:
    executable: /bin/bash
    chdir: /opt/mailcow-dockerized/

# intermittently the script uses the busybox version of grep and fails, thus force bash
- name: Generate mailcow configuration using non-interactive script (only runs once).
  shell: ./generate_config_non_interactive.sh
  args:
    executable: /bin/bash
    chdir: /opt/mailcow-dockerized/
    creates: "{{ mc_install_dir }}/mailcow.conf"

- name: Insert additional subdomains into mailcow.conf for SSL certificate generation.
  lineinfile:
    path: "{{ mc_install_dir }}/mailcow.conf"
    regexp: "^ADDITIONAL_SAN"
    line: "ADDITIONAL_SAN={{ mc_nextcloud_subdomain }}.{{ mc_domain }}"
    state: present

- name: Insert watchdog notify email into mailcow.conf.
  lineinfile:
    path: "{{ mc_install_dir }}/mailcow.conf"
    regexp: "^#WATCHDOG_NOTIFY_EMAIL="
    line: "WATCHDOG_NOTIFY_EMAIL={{ mc_notify_email }}"
    state: present

# TODO: (optional)
#  Modify docker-compose to add a bind mount for Nextcloud with s3ql

- name: Pull docker images & start containers (WAIT a few minutes).
  docker_service:
    project_src: "{{ mc_install_dir }}"
    pull: yes
    state: present # equivalent to docker-compose up
