---
# This is adding rules to the INPUT chain, without touching other firewall rules
# rules created by docker or fail2ban should not be interfered with.
- name: Create firewall directory.
  file:
   path:  "{{ mc_root_path }}/etc/firewall"
   state: directory

- name: Copy script which adds Mailserver IPtables rules.
  copy:
    src:  add_mailserver_fw_rules.sh
    dest: "{{ mc_root_path }}/etc/firewall/add_mailserver_fw_rules.sh"
    mode: a+x

- name: Create systemd service to add Firewall Mailserver rules to iptables.
  copy:
    src:  firewall.service
    dest: "{{ mc_root_path }}/etc/systemd/system/firewall.service"
  notify:
  - reload systemd
  - restart firewall

- name: Enable Firewall Mailserver rules (on startup).
  service:
    name:    firewall.service
    enabled: yes
