---
# handlers file for ansible-mailcow

- name: restart systemd-logind
  service:
    name: systemd-logind
    state: restarted
  when: >
    ansible_service_mgr == 'systemd'

- name: reload systemd
  command: systemctl daemon-reload

- name: restart firewall
  service:
    name: firewall.service
    state: restarted
